language: cpp
sudo: required
    
matrix:
  include:
  # Build Peepcoin-qt MAC
  # OS X 10.13 (High Sierra)
  - os: osx
    sudo: required
    before_install:
        brew install git; 
        brew install berkeley-db4;
        brew install openssl; 
        brew install boost@1.60; 
        brew link boost@1.60 -f; 
        brew install qt5; 
        brew link qt5 -f; 
        brew install libqrencode; 
        sudo easy_install appscript; 
        brew install wget;
        wget -O miniupnpc.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.20150206.tar.gz;
        tar xvzf miniupnpc.tar.gz; 
        mv miniupnpc-1.9.20150206 miniupnpc; 
        cd miniupnpc; 
        make -f Makefile upnpc-static; 
        sudo INSTALLPREFIX=/usr/local make install; 
    install: 
        cd  ${TRAVIS_BUILD_DIR};
        chmod 755 src/leveldb/build_detect_platform;
        qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 Peepcoin-qt.pro;
    script: make;
        export QTDIR=/usr/local/Cellar/qt/5.12.3;
        chmod -R 755 contrib;
        echo "Before dmg packaging";
        T=$(contrib/qt_translations.py $QTDIR/translations src/qt/locale);
        python2.7 contrib/macdeploy/macdeployqtplus  -add-qt-tr $T -dmg -fancy contrib/macdeploy/fancy.plist Peepcoin-Qt.app;
        ls -ltr;
        echo "DMG file";
  
  # Build Peepcoin-qt
  # Compile linux gui
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        cd  ${TRAVIS_BUILD_DIR};
        bash doc/unix-deps-install.sh;
    install: cd  ${TRAVIS_BUILD_DIR};
             chmod 755 src/leveldb/build_detect_platform;
             qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 Peepcoin-qt.pro;
    script: make;
        strip peepcoin-qt;
        tar -czvf peepcoin-qt.tar.gz peepcoin-qt;
  
  # Build Peepcoind
  # Compile linux daemon
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
        cd  ${TRAVIS_BUILD_DIR};
        bash doc/unix-deps-install.sh;
    install: cd  ${TRAVIS_BUILD_DIR};
             chmod 755 src/leveldb/build_detect_platform;
    script: cd  ${TRAVIS_BUILD_DIR}/src; 
        make -f makefile.unix RELEASE=1 STATIC=1;
        strip peepcoind;
        tar -czvf peepcoind.tar.gz peepcoind;
    
  # Build Peepcoin
  # Cross-compile Windows 32-bit 
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
    script: bash src/mxe-build.sh windows32-qt;

  # Build Peepcoin
  # Cross-compile Windows 64-bit 
  - os: linux
    dist: xenial
    sudo: required
    before_install:
        sudo /etc/init.d/postgresql stop;
        sudo systemctl enable mysql;
        sudo service mysql start;
        sudo apt dist-upgrade;
        sudo systemctl disable mysql;
    script: bash src/mxe-build.sh windows64-qt;

deploy:
  provider: releases
  api_key:
    secure: O8nodqyxLFe1UWuY4MK0ApN69PjoakPfVNihmPOtsqkeVdsRhsm3jEH8JdAzL5tmoGUzyPyGDYws6s4ilGeU981CITsJpfzwhGFvphIOJA2/jg+t+IwJ2t/I2JIe19zQ1LkoOHSQV29uZF0d9Nz2uYHl0S4CQFuEQs6B44thWaFWfabDzv+7tgjsoeaipi2jaUMUt4Cen9KmdXm+sgQBeYA10IIXpZE2H/J0wLjI1ppZCf94Y4MkY5ixXYbi9fKXweGD0pEXnwRXA1IqsLy6nLLHzEElvqnvwhdYhGVCGX4r5wsQCBMRQBRFk9R+HYjNlG2r00t6ULjilHdd3GQUUir9AYRQYHoBMnr5cfE4rwrTV8JuGcoMLkQ+4zdqIkACyS6kc5OPp++TfMGt/z6YQPIWWmt5S3AFTKBwP3g9CRbBrOKFNv86kygln1URtrA8U74BuqHmd9CM/vJz0Yul0jqGCmb0O0Pb/FkFPgJMbdr1UL1IAf3NkPkSe1B/ssrkoZjjGHCQ2hg3GCOcllSL7mPtjt2DT7HvbP2oKR1+1dneObMg0RjfBamOPknZjmVxLGdMQMM5VjAQhlDGGW4I6spAYuIKhfYuzKYV9+gcE/W0poGqZV3n3C32Pwy0ETH0ae4LjJj3h+GxLDpJv+o6u6hp1TgV3/NvHMZul3r52cg=
  file: 
      - Peepcoin-Qt.dmg
      - peepcoin-qt.tar.gz
      - peepcoind.tar.gz
      - release/peepcoin-qt-i686.exe
      - release/peepcoin-qt-x86_64.exe
  skip_cleanup: true
  on:
    repo: PXN-Foundation/Peepcoin
    tags: true
    branch: QA
