language: cpp

os:
- osx

before_install:
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install git; brew install berkeley-db4;
  brew install openssl; brew install boost@1.60; brew link boost@1.60 -force; brew
  install qt5; brew link qt5 -force; brew install libqrencode; sudo easy_install appscript; brew install wget;
  wget -O miniupnpc.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.20150206.tar.gz;
  tar xvzf miniupnpc.tar.gz; mv miniupnpc-1.9.20150206 miniupnpc; cd miniupnpc; make
  -f Makefile upnpc-static; sudo INSTALLPREFIX=/usr/local make install; fi

install:
- ls -ltr
- cd  ${TRAVIS_BUILD_DIR}
- chmod 755 src/leveldb/build_detect_platform
- qmake RELEASE=1 USE_UPNP=1 USE_QRCODE=1 Peepcoin-qt.pro

script:
- make

before_deploy:
- export QTDIR=/usr/local/Cellar/qt/5.11.1
- chmod -R 755 contrib
- echo "Before dmg packaging"
- T=$(contrib/qt_translations.py $QTDIR/translations src/qt/locale)
- python2.7 contrib/macdeploy/macdeployqtplus  -add-qt-tr $T -dmg -fancy contrib/macdeploy/fancy.plist Peepcoin-Qt.app
- ls -ltr
- echo "DMG file"

deploy:
  provider: releases
  api_key:
    secure: "USE VALID travis setup release, encrypted oath token"
  file: "Peepcoin-Qt.dmg"
  skip_cleanup: true
  on:
    repo: PXN-Foundation/Peepcoin
    tags: true
